language: php

php:
  - 5.6
  - 7.0

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - xmllint --noout --schema src/schema/config.xsd examples/config.xml
  - xmllint --noout --schema src/schema/menu.xsd examples/menu.xml
  - xmllint --noout --schema src/schema/plugin.xsd examples/plugin.xml
  - ./vendor/bin/phpunit --debug

notifications:
  email: false
